"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_Initial.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o Initial.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_InsertMin.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o InsertMin.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_InsertMin_Step1.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o InsertMin_Step1.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_InsertMin_Step2.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o InsertMin_Step2.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_RemoveMin.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o RemoveMin.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_RemoveMin_Step1.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o RemoveMin_Step1.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_RemoveMin_Step2.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o RemoveMin_Step2.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_RemoveMin_Step3.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o RemoveMin_Step3.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_RemoveMin_Step4.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o RemoveMin_Step4.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_RemoveMin_Step5.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o RemoveMin_Step5.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_RemoveMin_Step6.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o RemoveMin_Step6.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_Exercise_TreeValid_01.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o Exercise_TreeValid_01.png 
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_Exercise_TreeValid_02.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o Exercise_TreeValid_02.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_Exercise_TreeValid_03.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o Exercise_TreeValid_03.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_Exercise_TreeValid_04.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o Exercise_TreeValid_04.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_Exercise_Insert.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o Exercise_Insert.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_Exercise_Insert_Result.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o Exercise_Insert_Result.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_Exercise_Remove.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o Exercise_Remove.png
"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe" BinaryHeap_Exercise_Remove_Result.gv | "C:\Program Files (x86)\Graphviz2.38\bin\gvpr.exe" -c -ftree.gv | "C:\Program Files (x86)\Graphviz2.38\bin\neato.exe" -n -Tpng -o Exercise_Remove_Result.png
